ferme/urls.py
from django.contrib import admin
from django.urls import path ,include
from core.url import urlpatterns
from clientes.url import urlpatterns as clientes_url
from producto.url import urlpatterns as producto_url
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
   
    path('',include(urlpatterns)),

    path('signup/',include(clientes_url)),
    #path auth
    path('accounts/',include('django.contrib.auth.urls')),
    path('producto/',include(producto_url)),
    
   

]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

clientes/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class tipoCliente(models.Model):
    descripcion = models.CharField(verbose_name="tipo de cliente",max_length=200)

    class Meta:
        verbose_name = "Tipo cliente"
        verbose_name_plural = "Tipo cliente"
        

    def __str__(self):
        return self.descripcion
class Cliente(User):
    rut=models.CharField(verbose_name="rut cliente",max_length=20)
    nombre=models.CharField(verbose_name="nombre",max_length=200)
    fecha_nac=models.DateField(verbose_name="fecha de nacimiento")
    tipo_cliente=models.ForeignKey(tipoCliente , verbose_name="tipo de cliente",on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"
        

    def __str__(self):
        return self.nombre

core/models.py
from django.db import models
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext as _

# Create your models here.

producto/models.py
from django.db import models
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext as _
#importando la clase clientes
from clientes.models import Cliente
from django.contrib.auth import get_user_model
# Create your models here.

class familia(models.Model):
    nombreFamilia = models.CharField(max_length = 100)
    descripcionFamilia = models.TextField()

    class Meta:
        verbose_name="Familia Producto"

    def __str__(self):
        return self.nombreFamilia

class categoria(models.Model):
    nombreCategoria = models.CharField(max_length = 150)
    descripcionCategoria = models.TextField()
    nomFamilia = models.ForeignKey(familia, null=False, blank=False, on_delete=models.CASCADE)

    class Meta:
        verbose_name="Categoría"

    def __str__(self):
        return self.nombreCategoria

class producto(models.Model):
    fotografiaProducto = models.ImageField(upload_to = "media") 
    codigoProducto = models.CharField(max_length = 100)
    nombreProducto = models.CharField(max_length = 100)
    precioProducto = models.BigIntegerField()
    stockProducto = models.BigIntegerField()
    stockCriticoProducto = models.BigIntegerField()
    fechaVencimientoProducto = models.DateField()
    descripcionProducto = models.TextField()
    nomCategoria = models.ForeignKey(categoria, null=False, blank=False, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombreProducto

class carritoCompras(models.Model):
    producto=models.ForeignKey(producto, verbose_name="producto",on_delete=models.CASCADE)
    usuario=models.ForeignKey(get_user_model(),verbose_name="cliente", on_delete=models.CASCADE)
    precio = models.IntegerField()
    cantidad=models.IntegerField()
    comprado = models.BooleanField(default = False)
    pendiente = models.BooleanField(default = False)

    def __str__(self):
        return "{} {}".format(self.usuario, self.producto)

clientes/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from . models import Cliente


class ClienteForm(UserCreationForm):
    
    
    class Meta:
        model=Cliente
        fields=("rut","nombre","fecha_nac","username","email","password1","password2","tipo_cliente")
        widgets={
            #escribimoa el campo y le damos los atributos con attrs
            'fecha_nac':forms.DateInput(attrs={
            'class': 'datepicker'
            
        }),
            
        }

producto/forms.py
from django import forms

from .models import producto

class ProductosForm(forms.ModelForm):
    class Meta:
        model = producto
        fields = ('fotografiaProducto', 'codigoProducto', 'nombreProducto', 'precioProducto', 'stockProducto', 'stockCriticoProducto', 'fechaVencimientoProducto', 'descripcionProducto', 'nomCategoria')

clientes/views.py
from .forms import ClienteForm
from django.views.generic import CreateView
from django.urls import reverse_lazy 

# Create your views here.

class RegitroCliente(CreateView):
    form_class=ClienteForm
    
    template_name="registration/signup.html"
    def get_success_url(self):
        return reverse_lazy('login')

"""
def signup(request):
    form = UserCreationForm()
    return render(request,'registration/signup.html',{'form':form})
"""

core/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request,"core/home.html")
def contacto(request):
    return render(request,"core/contacto.html")
def quienesSomos(request):
    return render(request,"core/quienesSomos.html")
def servicios(request):
    return render(request,"core/servicios.html")

producto/views.py
from django.shortcuts import render
from .forms import ProductosForm
from .models import producto,categoria, carritoCompras
from django.urls import reverse
from django.urls import reverse_lazy, reverse
#importando las vistas genericas
from django.views.generic.list import ListView
from django.views.generic import DetailView, CreateView, RedirectView


# Create your views here.

def agregarProducto(request):
    if request.method == "POST":
        producto = ProductosForm(request.POST, request.FILES)
        if producto.is_valid():
            post = producto.save(commit=False)
            post.save()
    else:
        producto = ProductosForm()
    categorias = categoria.objects.order_by('nombreCategoria')
    return render(request,"producto/agregarProducto.html", {'producto': producto, 'categorias':categorias})


class DetalleProducto(DetailView):
    template_name="producto/detalle_producto.html"
    model=producto



class ListarProducto(ListView):
    template_name="producto/lista_producto.html"
    model=producto
    paginate_by=10
    #agregar funcion busqueda producto


class AnadirCarrito(CreateView):
    model = carritoCompras
    fields = ('producto', 'usuario', 'precio','cantidad',)
    success_url = reverse_lazy('lista_producto')
    login_url = 'login'

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{%block title%} Ferme Ferreterias{% endblock %}</title>
   
   
    {% load static%}
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link href="{%static 'core/css/materialize.css' %}" rel="stylesheet" media="screen,projection">
    <link href="{%static 'core/css/css.css' %}" rel="stylesheet">

</head>

<body>
    <!--cabecera-->
    <div class="cabecera" id="row-cabecera">
        <div class="row" >

            <div class="col 4">
                <img src="{%static 'core/img/logo.jpg'%}" alt="" id="logo">
            </div>
            <div class="col 4">
                <form action="" method="GET" class="buscar">
                    <div><input type="text" placeholder="Que busca?"></div>
                    <div> <input type="button" value="Buscar" class="btn-buscar"></div>

                </form>
            </div>
            <div class="col 4">

                {% if user.is_authenticated%}
                
                <p>Bienvenido <var style="color:blueviolet" >{{user.username}}</var>  | <a href="{% url 'logout'%}">Salir</a>|
                {% else%}
                <a href="{% url 'signup'%}">registrar</a>|
                <a href="{% url 'login'%}">ingresar</a></p>
               
                {%endif%}
              

            </div>

        </div>

        <div class="row" >
            <div class="col l6" >
                <p>Aca va el filtro</p>
                
            </div>
            <div class="col l6" >
                    
                    
                    <a href="{% url 'quienesSomos'%}" id="menu">quienes somos</a>
                    <a href="{% url 'contacto'%}" id="menu">contacto</a>
                    <a href="{% url 'servicios'%}" id="menu">Servicios</a>
                    <a href="{% url 'agregarProducto' %}" id="menu"> otros</a>
                    
                    
                </div>
        </div>

    </div>



    <!--contenido-->
    <div class="container">
        <!--aca va el contenido-->
        {%block content%}

        {%endblock%}

    </div>






    <!--scripts-->
    

</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<script src="{%static 'core/js/materialize.min.js' %}"></script>

<script type="text/javascript">
$(document).ready(function(){
$('select').formSelect();
});
$(document).ready(function(){
    $('.datepicker').datepicker({
        format:'dd/mm/yy'
    });
  });
</script>
</html>

core/templates/core/contacto.html
{%extends "core/base.html"%}
{%block content%}
<h1>contacto</h1>
{%endblock%}

<h1>contacto</h1>
<!--este comentario fue subido desde un branch-->

core/templates/core/home.html
{%extends "core/base.html"%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title></title>
    {%load static%}
    <!--aqui se cargaran los recursos -->
</head>
<body>
    
    <h1>pagina de pruebas Home</h1>
    <br>
    <nav>
        <li><a href="#">quienes somos </a></li>
        <li><a href="{% url 'contacto'%}">contato </a></li>
        <li><a href="{% url 'quienesSomos'%}">quienes somos </a></li>
    
        <li><a href="{% url 'agregarProducto'%}">Agregar Producto</a></li>
    </nav>
</body>
</html>

core/templates/core/quienesSomos.html
{%extends "core/base.html"%}

{%block content%}
<h1>quienes Somos</h1>
{%endblock%}
<h1>quienes Somos</h1>

core/templates/core/servicios.html
{%extends "core/base.html"%}

{%block content%}
<h1>Servicios</h1>
{%endblock%}

producto/templates/producto/agregarProducto.html
<!DOCTYPE html>{% load staticfiles %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Agregar Producto</title>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link rel="stylesheet" href="{% static 'css/flexboxgrid.min.css' %}">
</head>

<body>
    <header class="row">
        <div class="col-lg-2">
            <a tittle="LOGO" href="/"><img src="{% static 'img/logoFerme.png' %}" alt="LOGO"></a>
        </div>
        <div class="col-lg-1"></div>
        <div class="col-lg-6">
            <h1>AGREGAR PRODUCTO</h1>
        </div>
    </header>
    <hr>
    <main id="AgregarProducto" class="row">
        <div id="registroProducto" class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            {% block content %}
            <form name="producto" id="formularioProducto" enctype="multipart/form-data" method="POST" class="post-form">{% csrf_token %}

                <label>Fotografía:</label><br>
                <input type="file" name="fotografiaProducto" accept="image/*"><br><br>
                
                <label>Código Producto:</label><br><br>
                <input type="text" name="codigoProducto"><br><br>

                <label>Nombre:</label><br><br>
                <input type="text" name="nombreProducto"><br><br>

                <label>Precio:</label><br><br>
                <span>$</span> </h1> <input type="number" name="precioProducto"><br><br>

                <label>Stock:</label><br><br>
                <input type="number" name="stockProducto"><br><br>

                <label>Stock Crítico:</label><br><br>
                <input type="number" name="stockCriticoProducto"><br><br>

                <label>Fecha Vencimiento:</label><br><br>
                <input type="date" name="fechaVencimientoProducto"><br><br>

                <label>Descripción:</label><br><br>
                <textarea name="descripcionProducto" cols="30" rows="10"></textarea><br><br>

                <label>Categoría:</label><br><br>
                <select name="nomCategoria" id="nomCategoria">
                    <option value="Seleccionar">Seleccionar</option>
                    {% for categoria in categorias %}
                        <option value="{{ categoria.pk }}">{{ categoria.nombreCategoria }}</option>
                    
                    {% endfor %}
                </select><br><br>

                <button type="submit">Registrar</button>

                
            </form>
            {% endblock %}
            
        </div>
    </main>


</body>

</html>

producto/templates/producto/detalle_producto.html
{%extends "core/base.html"%}
{%block title%} 
Ferme Catalogo
{%endblock%}
{% load static %}
{%block content%}
<h1 >Producto: {{producto.nombreProducto}}</h1>

<hr>
<br>
<br>
<br>


<div class="row">

<class class="col">
<div class="card">
    <img style="width:300px" src="{{producto.fotografiaProducto.url}}" alt="">

  <p><label for="">Nombre producto :</label> {{producto.nombreProducto}}</p>
  <p><label for="">Precio producto :</label>$ {{producto.precioProducto}}</p>
  
  <form action="{% url 'anadir_carrito' %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="producto" value="{{producto.pk}}">
      <input type="hidden" name="usuario" value="{{request.user.pk}}">
      <input type="hidden" name="precio" value="{{producto.precioProducto}}">
      <span>Cantidad: <input type="number" name="cantidad"></span>
      
      <button type="submit">Agregar al Carro</button>
      
  </form>  
        
</div>

</class>

</div>

{%endblock%}

producto/templates/producto/lista_producto.html
{%extends "core/base.html"%}
{%block title%} 
Ferme Catalogo
{%endblock%}
{% load static %}
{%block content%}
<h1 >Productos</h1>

<hr>
<br>
<br>
<br>


<div class="row">
{% for producto in producto_list%}
<class class="col">
<div class="card">
    <img style="width:300px" src="{{producto.fotografiaProducto.url}}" alt="">

  <p><label for="">Nombre producto :</label> {{producto.nombreProducto}}</p>
  <p><label for="">Precio producto :</label>$ {{producto.precioProducto}}</p>
  <p><a href="{% url 'detalle_producto' producto.id producto.nombreProducto|slugify %}">Leer más</a>
    
            
</div>
  

</class>

{% endfor%}
</div>

{%endblock%}